# Generated by Django 6.0.2 on 2026-03-27 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especie', models.CharField(default='Canina', max_length=50)),
                ('raca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Raça')),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1)),
                ('idade_anos', models.IntegerField(default=0, verbose_name='Anos')),
                ('idade_meses', models.IntegerField(default=0, verbose_name='Meses')),
                ('pelagem_tamanho', models.CharField(choices=[('CURTO', 'Curto'), ('MEDIO', 'Médio'), ('LONGO', 'Longo')], default='CURTO', max_length=20)),
                ('pelagem_cor', models.CharField(blank=True, max_length=50, null=True)),
                ('tomou_dose_1', models.BooleanField(default=False, verbose_name='1ª Dose')),
                ('data_dose_1', models.DateField(blank=True, null=True)),
                ('tomou_dose_2', models.BooleanField(default=False, verbose_name='2ª Dose')),
                ('data_dose_2', models.DateField(blank=True, null=True)),
                ('tomou_dose_3', models.BooleanField(default=False, verbose_name='3ª Dose (Reforço)')),
                ('data_dose_3', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUSPEITO', 'Suspeito'), ('POSITIVO', 'Positivo (Confirmado)'), ('NEGATIVO', 'Negativo'), ('OBITO', 'Óbito'), ('EM_TRATAMENTO', 'Em Tratamento')], default='SUSPEITO', max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pets/')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_inicio', models.DateField()),
                ('dose', models.CharField(blank=True, max_length=100, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicacoes', to='pacientes.pet')),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='proprietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='pacientes.proprietario'),
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_visita', models.DateField()),
                ('tipo_inquerito', models.CharField(choices=[('CENSITARIO', 'Censitário'), ('AMOSTRAL', 'Amostral'), ('ESPONTANEO', 'Demanda Espontânea')], default='CENSITARIO', max_length=20)),
                ('tem_emagrecimento', models.BooleanField(default=False, verbose_name='Emagrecimento')),
                ('tem_alopecia', models.BooleanField(default=False, verbose_name='Alopecia (Queda de Pelo)')),
                ('tem_descamacao', models.BooleanField(default=False, verbose_name='Descamação/Caspa')),
                ('tem_onicogrifose', models.BooleanField(default=False, verbose_name='Onicogrifose (Unhas Grandes)')),
                ('tem_feridas', models.BooleanField(default=False, verbose_name='Feridas/Úlceras')),
                ('resultado_elisa', models.CharField(choices=[('REAGENTE', 'Reagente'), ('NAO_REAGENTE', 'Não Reagente'), ('NAO_REALIZADO', 'Não Realizado')], default='NAO_REALIZADO', max_length=20)),
                ('resultado_dpp', models.CharField(choices=[('REAGENTE', 'Reagente'), ('NAO_REAGENTE', 'Não Reagente'), ('NAO_REALIZADO', 'Não Realizado')], default='NAO_REALIZADO', max_length=20)),
                ('usa_coleira', models.BooleanField(default=False)),
                ('vacinado', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='pacientes.pet')),
            ],
        ),
        migrations.CreateModel(
            name='FotoEvolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='evolucao/')),
                ('legenda', models.CharField(blank=True, max_length=255, null=True)),
                ('data_registro', models.DateField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='pacientes.pet')),
                ('visita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotos_clinicas', to='pacientes.visita')),
            ],
        ),
    ]
