# Generated by Django 6.0.2 on 2026-02-04 03:58

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=20)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especie', models.CharField(default='Canina', max_length=50)),
                ('raca', models.CharField(blank=True, max_length=100, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1)),
                ('idade_aproximada', models.IntegerField(blank=True, help_text='Idade em anos', null=True)),
                ('status', models.CharField(choices=[('SUSPEITO', 'Suspeito'), ('POSITIVO', 'Positivo (Confirmado)'), ('NEGATIVO', 'Negativo'), ('EM_TRATAMENTO', 'Em Tratamento'), ('OBITO', 'Óbito')], default='SUSPEITO', max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pets/')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='pacientes.proprietario')),
            ],
        ),
    ]
