# Generated by Django 6.0.2 on 2026-02-04 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='idade_aproximada',
        ),
        migrations.RemoveField(
            model_name='proprietario',
            name='geometry',
        ),
        migrations.AddField(
            model_name='pet',
            name='idade_anos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proprietario',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proprietario',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('SUSPEITO', 'Suspeito'), ('POSITIVO', 'Positivo (Confirmado)'), ('NEGATIVO', 'Negativo'), ('OBITO', 'Óbito')], default='SUSPEITO', max_length=20),
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_visita', models.DateField()),
                ('tipo_inquerito', models.CharField(choices=[('CENSITARIO', 'Censitário'), ('AMOSTRAL', 'Amostral'), ('ESPONTANEO', 'Demanda Espontânea')], default='CENSITARIO', max_length=20)),
                ('tem_emagrecimento', models.BooleanField(default=False, verbose_name='Emagrecimento')),
                ('tem_alopecia', models.BooleanField(default=False, verbose_name='Alopecia (Queda de Pelo)')),
                ('tem_descamacao', models.BooleanField(default=False, verbose_name='Descamação/Caspa')),
                ('tem_onicogrifose', models.BooleanField(default=False, verbose_name='Onicogrifose (Unhas Grandes)')),
                ('tem_feridas', models.BooleanField(default=False, verbose_name='Feridas/Úlceras')),
                ('resultado_elisa', models.CharField(choices=[('REAGENTE', 'Reagente'), ('NAO_REAGENTE', 'Não Reagente'), ('NAO_REALIZADO', 'Não Realizado')], default='NAO_REALIZADO', max_length=20)),
                ('resultado_dpp', models.CharField(choices=[('REAGENTE', 'Reagente'), ('NAO_REAGENTE', 'Não Reagente'), ('NAO_REALIZADO', 'Não Realizado')], default='NAO_REALIZADO', max_length=20)),
                ('usa_coleira', models.BooleanField(default=False)),
                ('vacinado', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='pacientes.pet')),
            ],
        ),
    ]
