# Generated by Django 6.0.2 on 2026-02-04 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_remove_pet_idade_aproximada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='data_dose_1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='data_dose_2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='data_dose_3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='idade_meses',
            field=models.IntegerField(default=0, verbose_name='Meses'),
        ),
        migrations.AddField(
            model_name='pet',
            name='pelagem_cor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='pelagem_tamanho',
            field=models.CharField(choices=[('CURTO', 'Curto'), ('MEDIO', 'Médio'), ('LONGO', 'Longo')], default='CURTO', max_length=20),
        ),
        migrations.AddField(
            model_name='pet',
            name='tomou_dose_1',
            field=models.BooleanField(default=False, verbose_name='1ª Dose'),
        ),
        migrations.AddField(
            model_name='pet',
            name='tomou_dose_2',
            field=models.BooleanField(default=False, verbose_name='2ª Dose'),
        ),
        migrations.AddField(
            model_name='pet',
            name='tomou_dose_3',
            field=models.BooleanField(default=False, verbose_name='3ª Dose (Reforço)'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='idade_anos',
            field=models.IntegerField(default=0, verbose_name='Anos'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='raca',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Raça'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('SUSPEITO', 'Suspeito'), ('POSITIVO', 'Positivo (Confirmado)'), ('NEGATIVO', 'Negativo'), ('OBITO', 'Óbito'), ('EM_TRATAMENTO', 'Em Tratamento')], default='SUSPEITO', max_length=20),
        ),
    ]
