# Generated by Django 6.0.2 on 2026-03-06 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_medicacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoEvolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='evolucao/')),
                ('legenda', models.CharField(blank=True, max_length=255, null=True)),
                ('data_registro', models.DateField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='pacientes.pet')),
                ('visita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotos_clinicas', to='pacientes.visita')),
            ],
        ),
    ]
